# Generated by Django 5.0.2 on 2025-03-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_name', models.CharField(max_length=50)),
                ('support_email', models.EmailField(max_length=254)),
                ('support_date', models.DateField()),
                ('support_time', models.TimeField()),
            ],
        ),
    ]
